---
name: Release
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - release/**
jobs:
  release:
    uses: dropwizard/workflows/.github/workflows/release.yml@main
    secrets: inherit
